---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(deSolve)
library(dplyr)
```



THIS FILE IS USED TO SIMULATE THE NECESSARY DATA

#GENERAL RUNDOWN



##FIXED VARIABLES

```{r Default Values}
DEF_A <- seq(0.1, 1, 0.09)
DEF_B <- seq(0.01, 0.8, 0.079)
DEF_C <- seq(0.072, 0.64, 0.0568)
DEF_GAMMA <- seq(0.005, 0.05, 0.0045)
DEF_MU <- seq(0.05, 0.33, 0.028)
```


## PARAMATERS TO TEST

Insert which parameters you want to test here.

```{r Params}
PARAMS <- c(0.7, 0.2, 0.6, 100, 100, 0.04, 0.25, 1, 10, 10)
```

## DATA TITLE 

```{r Data Name}
PARAMSTR <- ""
for (i in 1:10){
  PARAMSTR <- paste(PARAMSTR, "-", as.character(PARAMS[i]), sep = "")
}

DATANAME <- paste("EEB313FinalData8", PARAMSTR, ".csv", sep = "")
SUBDATANAME <- paste("EEB313FinalSubdata8", PARAMSTR, ".csv", sep = "")
```

```{r Indicators}
paramsIndicator <- expand.grid(c(0,1), c(0,1), c(0,1), 
                               c(0,1), c(0,1))
paramsIndicator <- subset(paramsIndicator, rowSums(paramsIndicator) < 3) 
  row.names(paramsIndicator) <- 1:nrow(paramsIndicator)
```

```{r Appying Indicators}
applyIndicator <- function(params,
                           value,
                           binary){
  if (binary == 0){
    return(value)
  }
  else
    return(params)
}
```

```{r}
calc_rates <- function(state, parameters) {
  Ih <- state[1]
  Iv <- state[2]
  H <- parameters$H
  V <- parameters$V
  a <- parameters$a
  b <- parameters$b
  c <- parameters$c
  gamma <- parameters$gamma
  mu <- parameters$mu
  
  propensities <- c(
    ((H-Ih)* a * b * Iv)/ H, # infection of human
    ((V - Iv)* a * c * Ih)/ H,  # infection of vector
    gamma * Ih, # recovery of human
    mu * Iv # death of vector
  )
  
  return(propensities)
}

nu <- matrix(c(+1, 0, -1, 0,
               0, +1, 0, -1), 
             nrow = 2, byrow = TRUE)

calc_event <- function(state, parameters) {
  rates <- calc_rates(state, parameters)
  total_rate <- sum(rates)
  
  tau <- rexp(1, rate = total_rate)
  
  event_probabilities <- rates / total_rate
  event <- sample(1:length(rates), size = 1, prob = event_probabilities)
  
  return(list(tau, event))
}

initial_state <- c(Ih = PARAMS[9], Iv = PARAMS[10])  
parameters <- list(H = PARAMS[4], V = PARAMS[5], a = PARAMS[1], b = PARAMS[2], 
                   c = PARAMS[3], gamma = PARAMS[6], mu = PARAMS[7])
total_time <- 5000

gillespie_full <- function(initial_state, parameters, total_time) {
  
  t <- 0
  i <- 1
  state <- matrix(initial_state, nrow=1)
  times <- c(t)

  while (t < total_time) {
    
    if (state[i,1] == 0 & state[i,2] == 0){
      break
    }
    
    step_result <- calc_event(state[i,], parameters)
    
    t <- t + step_result[[1]]
    state <- rbind(
      state,
      state[i,] + nu[,step_result[[2]]]
    )
    
    if (state[i+1,1] > parameters$H){
      state[i+1,1] <- parameters$H
    }
    
    if (state[i+1,2] > parameters$V){
      state[i+1,2] <- parameters$V
    }
    
    times <- c(times, t)
    i <- i+1
  }
  
  colnames(state) <- c("Ih", "Iv")
  
  return(cbind(times,  state))
}

df <- c()
nsims <- 1

for (j in 1:nsims){
  df <- rbind(df, cbind(
    gillespie_full(initial_state, parameters, total_time),
    index = j))
}
```


```{r, warning=FALSE}
rossMacOde <- function(times, state, params){
  with(as.list(c(state,params)),{
    dIh <- (a * b * Iv * (H - Ih))/H - gamma * Ih
    dIv <- (a * c * Ih * (V - Iv))/H - mu * Iv
    
    return(list(c(dIh, dIv)))
  })
}

state <- c(Ih = PARAMS[9], Iv = PARAMS[10])   # define initial conditions
times <- seq(0, 5000, 0.01)

do.call(cbind, parameters) -> params_to_use
df_LL_params <- c(params_to_use[1,3:7], LogLik = 0)

out <- as.data.frame(ode(state, times, rossMacOde, params_to_use[1,]))

df_index <- df |> subset(df[,4] == 1)
    as.data.frame(df_index) |> 
      mutate(reporting_times = round(times)) %>% 
      group_by(reporting_times) %>%
      summarize(Ih = mean(Ih),
                Iv = mean(Iv)) -> df_rounded
    
      return_LL_at_specific_combo_params <- function(params_to_use){
    
    out <- as.data.frame(ode(state, times, rossMacOde, params_to_use)) |>
      subset(time %in% unique(df_rounded$reporting_times))
    # solve model for particular set of parameters
    # keep variables only at observation times
    
    LL <- c()
    
    for (i in 1:length(df_rounded$reporting_times)){
      LL[i] <- dnorm(as.numeric(df_rounded[i,2]), 
                     mean = out$Ih[i], 
                     sd = params$sigma,
                     log = TRUE)
    }
    # calculate likelihood of data at observation times
    # based on assumption data are Normal around the solution at a given time
    
    LogLik <- sum(LL[! is.na(LL)])
    # calculate log-likelihood of parameters given ALL data
    
    return(data.frame(params_to_use, LogLik = LogLik))
  }


for (j in 1:nrow(paramsIndicator)){
params <- expand.grid(a = applyIndicator(DEF_A, PARAMS[1], paramsIndicator[j,1]),
                     b = applyIndicator(DEF_B, PARAMS[2], paramsIndicator[j,2]),
                     c = applyIndicator(DEF_C, PARAMS[3], paramsIndicator[j,3]), 
                     gamma = applyIndicator(DEF_GAMMA, PARAMS[6], paramsIndicator[j,4]), 
                     mu = applyIndicator(DEF_MU, PARAMS[7], paramsIndicator[j,5]),
                     H = PARAMS[4], 
                     V = PARAMS[5],
                     sigma = PARAMS[8]
                     )
# many parameters fixed for convenience, but in general could / often should be fitted!
  
  LogLikihoods <- NULL
  
  for (i in 1:nrow(params)){
    LogLikihoods <- rbind(LogLikihoods, 
                          return_LL_at_specific_combo_params(params[i,])
                          )
    print(c(j,i))
  }
  
  MLE <- LogLikihoods %>% subset(is.finite(LogLik)) %>% 
    subset(LogLik == max(LogLik))
  
  df_LL_params <- rbind(df_LL_params, select(MLE[1,], ! c(sigma,H, V)))
}

# out_estimated <- as.data.frame(ode(state, times, rossMacOde, MLE[1,]))
```

```{r}
infected_output <- as.data.frame(cbind(time = out$time, 
                                       Ih = out$Ih)) %>% 
  subset(time %in% df_rounded$reporting_times) %>% 
  cbind(Ih_gil = df_rounded$Ih)


write_csv(infected_output, DATANAME)
write_csv(df_LL_params, SUBDATANAME)
```

